# Generated by Django 3.0.8 on 2020-09-30 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('last_name', models.CharField(max_length=55)),
                ('birthday_date', models.DateField()),
                ('bio', models.TextField(verbose_name='Biography')),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='')),
                ('email', models.EmailField(max_length=115)),
                ('jabber', models.CharField(max_length=115)),
                ('skype', models.CharField(max_length=115)),
                ('other_contacts', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
