# Generated by Django 3.0.8 on 2020-10-05 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestmodel',
            name='priority',
            field=models.IntegerField(default=1),
        ),
    ]
