# Generated by Django 3.0.8 on 2020-10-05 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0002_requestmodel_priority'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='requestmodel',
            options={'get_latest_by': 'id', 'ordering': ('-priority', '-timestamp')},
        ),
    ]
