# Generated by Django 3.0.8 on 2020-10-06 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0003_auto_20201005_1403'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='requestmodel',
            options={'get_latest_by': 'id', 'ordering': ('-timestamp',)},
        ),
    ]
